defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

model_params:
  multi_class: multinomial
  max_iter: 500
  solver: lbfgs

train_params:
  data_path: irises_classification/dataset/train.csv
  model_path: irises_classification/models/model.pkl

infer_params:
  data_path: irises_classification/dataset/val.csv
  model_path: irises_classification/models/model.pkl
  prediction_path: irises_classification/results/result.csv

server_params:
  uri: http://127.0.0.1:8080
  exp_name: log_reg_default_params
