defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

train:
  data_path: irises_classification/dataset/train.csv
  model_path: irises_classification/models/model.pkl

infer:
  data_path: irises_classification/dataset/val.csv
  model_path: irises_classification/models/model.pkl
  prediction_path: irises_classification/results/result.csv
